// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWYzFywP8hdzrlna5LGl5kS3A-WHE2D8A',
    appId: '1:578954040405:web:d8432d05aa36d1b96570dc',
    messagingSenderId: '578954040405',
    projectId: 'catalogo-peliculas-4e224',
    authDomain: 'catalogo-peliculas-4e224.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-4e224.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvXLWDLb4cMGZkP4DEPXrSVKvOUToJqAE',
    appId: '1:578954040405:android:3a4d76f9c551bbab6570dc',
    messagingSenderId: '578954040405',
    projectId: 'catalogo-peliculas-4e224',
    storageBucket: 'catalogo-peliculas-4e224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8akDJV1HjKbFp4mFoI8I9tabrdGk09I',
    appId: '1:578954040405:ios:21ece05b50b080376570dc',
    messagingSenderId: '578954040405',
    projectId: 'catalogo-peliculas-4e224',
    storageBucket: 'catalogo-peliculas-4e224.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL8akDJV1HjKbFp4mFoI8I9tabrdGk09I',
    appId: '1:578954040405:ios:21ece05b50b080376570dc',
    messagingSenderId: '578954040405',
    projectId: 'catalogo-peliculas-4e224',
    storageBucket: 'catalogo-peliculas-4e224.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWYzFywP8hdzrlna5LGl5kS3A-WHE2D8A',
    appId: '1:578954040405:web:94a31bbb7b6a00fc6570dc',
    messagingSenderId: '578954040405',
    projectId: 'catalogo-peliculas-4e224',
    authDomain: 'catalogo-peliculas-4e224.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-4e224.firebasestorage.app',
  );
}
